Add block exchange, histogram, select_if, scan and reduce benchmarks
allisonvacanti/thrust_benchmark pull request #2
Opened 2021-06-01 10:50 UTC by senior-zero

2021-06-01 18:41 UTC, allisonvacanti requested changes
These look great overall, most of my comments are nitpicks :)

2021-06-01 18:41 UTC, alliepiper commented on benches/cub/block/exchange/block_exchange.cuh
> +  typedef cub::BlockExchange<T, ThreadsInBlock, ItemsPerThread, WarpTimeSlicing>
Prefer `using` aliases over typedefs in new code.

2021-06-01 18:41 UTC, alliepiper commented on benches/cub/block/exchange/block_exchange.cuh
> +  const auto blocks           = static_cast<size_t>(state.get_int64("Blocks"));
Use `std::size_t` instead of `size_t` (using the library type may become more important as libcu++ evolves)

2021-06-01 18:41 UTC, alliepiper commented on benches/cub/block/exchange/block_exchange.cuh
> +  const unsigned int elements = blocks;
Needs a cast to avoid narrowing warnings.

2021-06-01 18:41 UTC, alliepiper commented on benches/cub/block/exchange/block_exchange.cuh
> +    if (compute_mode::reference == ComputeMode)
Since `ComputeMode` is compile-time constant, `if constexpr` would ensure that we're only doing the necessary codegen here.

2021-06-01 18:41 UTC, alliepiper commented on benches/cub/block/exchange/block_exchange.cuh
> +  const unsigned int elements = blocks;
Also, this variable is used in several contexts below that expect a `std::size_t`. Consider just using `blocks` directly, or renaming the `Blocks` axis to `Elements` -- this would be more consistent with the other benchmarks which all have an `Elements` axis.

2021-06-01 18:41 UTC, alliepiper commented on benches/cub/block/exchange/block_exchange.cuh
> +__global__ void kernel(const T *input, int *output)
It looks like `output` is always `nullptr` for all invocations. Is this expected? If so, can we document this behavior, and why this variable is needed?

2021-06-01 18:41 UTC, alliepiper commented on benches/cub/block/exchange/scatter_to_striped_flagged.cu
> +// TODO There is a bug in ScatterToStripedFlagged with WARP_TIME_SLICE option
Can you file a bug for this, if you haven't already fixed it?

2021-06-01 18:41 UTC, alliepiper commented on benches/cub/block/exchange/scatter_to_striped_guarded.cu
> +// TODO There is a bug in ScatterToStripedGuarded with WARP_TIME_SLICE option
Same note as earlier.

2021-06-01 18:41 UTC, alliepiper commented on benches/tbm/range_generator.cuh
> +[[nodiscard]] auto make_range_generator(std::size_t size, std::size_t modulo=1)
Hmmm...no objections to this for now, but we should think of a more maintainable/scalable way to pass pattern-specific parameters here. But we can solve that later.

2021-06-01 18:41 UTC, alliepiper commented on benches/tbm/range_generator.cuh
> +[[nodiscard]] auto make_range_generator(std::size_t size, std::size_t modulo=1)
Maybe we can make this a template parameter `InitOptions` and provide multiple overloads of `init` that will validate the combination of pattern/style/init parameters.

2021-06-01 18:41 UTC, alliepiper commented on benches/cub/device/histogram/even.cu
> +  // Compilation is broken for size_t, why?
Did you get a chance to look into this?

2021-06-01 18:41 UTC, allisonvacanti commented on benches/cub/device/histogram/range.cu
> +  // Compilation is broken for size_t, why?
Same as above

2021-06-01 18:41 UTC, allisonvacanti commented on benches/cub/device/reduce/complex.cu
> +// Sweep though various input iterators and patterns using cub::Max and
This comment looks unrelated. Can we rename this file to `complex_op.cu`? The name `complex` sounds like it's benchmarking reductions of complex numbers (e.g. `thrust::complex`)

2021-06-01 18:41 UTC, allisonvacanti commented on benches/cub/device/scan/inclusive_scan/basic.cu
> +#include <nvbench/nvbench.cuh>
Let's rename this file to `complex_op` as well.

2021-06-01 18:41 UTC, allisonvacanti commented on benches/cub/device/scan/inclusive_scan/basic.cu
> +  .set_timeout(21)
Ideally we shouldn't hardcode these values for timeout, max_noise, and skip_time. I may have left these in some of the proof-of-concept benchmarks, but we should remove them and avoid them in new benchmarks unless absolutely necessary.

2021-06-01 18:41 UTC, allisonvacanti commented on benches/cub/device/select/if.cu
> +#include <nvbench/nvbench.cuh>
Let's split this and `if_complex` into

```
benches/cub/device/select/if/basic.cu
benches/cub/device/select/if/complex_predicate.cu
```

to keep the generated test/executable names consistent.

2021-06-01 18:41 UTC, allisonvacanti commented on benches/cub/device/select/if.cu
> +  // complex
Maybe note that this case is covered in a different file.

2021-06-01 18:41 UTC, allisonvacanti commented on benches/cub/device/select/if.cu
> +    return gt_select_op<T> (elements / 2);
Remove the space and prefer `{}` to clarify that this is construction and not a call.

2021-06-01 18:41 UTC, allisonvacanti commented on benches/cub/device/select/if.cu
> +    return gt_select_op<T> (0);
Same.

2021-06-01 18:41 UTC, allisonvacanti commented on benches/cub/device/select/if.cu
> +  state.add_global_memory_reads(elements);
Missing a template parameter -- without specifying the type of the reads/writes, NVBench assumes that the argument is the raw number of bytes in the buffer. Also, use `range_generator::get_allocation_size` when possible. Some of the range generators compute values on-the-fly, and thus don't actually contribute to global memory bandwidth.

The number of writes will also depend on how many selected values there are. This should look something like:

```
state.add_element_count(elements);
state.add_global_memory_reads(input.get_allocation_size());
state.add_global_memory_writes<T>(selected_count);
```

2021-06-01 18:41 UTC, allisonvacanti commented on benches/cub/device/select/if_complex.cu
> +  state.add_global_memory_reads(elements);
Same note as in the other file.

2021-06-01 18:41 UTC, allisonvacanti commented on benches/cub/device/select/if.cu
> +  state.add_global_memory_reads(elements);
You can also move this bit after the kernel launch, in which case you can use the `num_selected` result to get an accurate count of the number of writes.

2021-06-02 11:29 UTC, senior-zero commented on benches/cub/device/histogram/even.cu
> +  // Compilation is broken for size_t, why?
It seems that the issue was fixed [here](https://github.com/NVIDIA/cub/commit/69513b733debbc4346eda56538e28be0344f7fa3). I'll delete the comment.

2021-06-02 13:54 UTC, senior-zero commented on benches/cub/block/exchange/scatter_to_striped_flagged.cu
> +// TODO There is a bug in ScatterToStripedFlagged with WARP_TIME_SLICE option
Sure, here is [the bug](https://github.com/NVIDIA/cub/issues/317).

2021-06-02 16:16 UTC, allisonvacanti approved these changes
One minor issue pointed out inline. Feel free to merge this once it's addressed.

2021-06-02 16:16 UTC, allisonvacanti commented on benches/cub/device/select/if/basic.cu
> +  using namespace nvbench::exec_tag;
This appears to be unused.

2021-06-02 16:25 UTC, merged